'use client';
import {ChangeEvent,useEffect,useMemo,useState} from 'react';
import {Check,ImagePlus,Pencil,Play,Plus,RotateCcw,Settings,Sparkles,Trash2,Users,X} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle,DialogTrigger} from '@/components/ui/dialog';
type Person={id:string;name:string;photo:string}; type Choice={value:string;correct:boolean};
const KEY='name-match-people-v1';
const similar:Record<string,string[]>={王:['玉','主'],玉:['王','主'],明:['朋','眀'],婷:['庭','亭'],晴:['睛','精'],睛:['晴','精'],宇:['字','守'],安:['按','案'],怡:['宜','依'],佳:['加','嘉'],嘉:['佳','加'],瑄:['宣','萱'],萱:['宣','瑄'],翔:['祥','詳'],祥:['翔','詳'],宏:['弘','洪'],弘:['宏','洪'],祐:['佑','右'],佑:['祐','右'],妤:['瑜','愉'],豪:['濠','毫'],毅:['義','議'],芯:['心','欣'],欣:['芯','心'],潔:['捷','婕']};
const extras='王玉主日目木禾大太天子字宇心芯欣佳加嘉晴睛精庭婷亭祥翔詳佑祐右';
function shuffle<T>(a:T[]){const r=[...a];for(let i=r.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[r[i],r[j]]=[r[j],r[i]]}return r}
function choices(answer:string,people:Person[]):Choice[]{const pool=[...(similar[answer]??[]),...people.flatMap(p=>Array.from(p.name)),...Array.from(extras)].filter((c,i,a)=>c!==answer&&a.indexOf(c)===i);return shuffle([{value:answer,correct:true},...shuffle(pool).slice(0,2).map(value=>({value,correct:false}))])}
async function resize(file:File){const source=await createImageBitmap(file),scale=Math.min(1,900/Math.max(source.width,source.height)),canvas=document.createElement('canvas');canvas.width=Math.round(source.width*scale);canvas.height=Math.round(source.height*scale);canvas.getContext('2d')?.drawImage(source,0,0,canvas.width,canvas.height);source.close();return canvas.toDataURL('image/jpeg',.82)}
export default function Game(){
 const [people,setPeople]=useState<Person[]>([]),[loaded,setLoaded]=useState(false),[open,setOpen]=useState(false),[name,setName]=useState(''),[photo,setPhoto]=useState(''),[editId,setEditId]=useState<string|null>(null),[current,setCurrent]=useState<Person|null>(null),[index,setIndex]=useState(0),[opts,setOpts]=useState<Choice[]>([]),[picked,setPicked]=useState<string|null>(null),[score,setScore]=useState(0),[round,setRound]=useState(0),[status,setStatus]=useState<'idle'|'playing'|'finished'>('idle'),[message,setMessage]=useState('');
 useEffect(()=>{try{setPeople(JSON.parse(localStorage.getItem(KEY)??'[]'))}catch{setPeople([])}setLoaded(true)},[]);useEffect(()=>{if(loaded)localStorage.setItem(KEY,JSON.stringify(people))},[people,loaded]);
 const reset=()=>{setName('');setPhoto('');setEditId(null)},upload=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f?.type.startsWith('image/'))setPhoto(await resize(f));e.target.value=''},save=()=>{if(!name.trim()||!photo)return;const p={id:editId??crypto.randomUUID(),name:name.trim(),photo};setPeople(a=>editId?a.map(x=>x.id===editId?p:x):[...a,p]);reset()},edit=(p:Person)=>{setEditId(p.id);setName(p.name);setPhoto(p.photo)},remove=(id:string)=>{setPeople(a=>a.filter(p=>p.id!==id));if(editId===id)reset()};
 const start=()=>{if(people.length<3){setOpen(true);return}let p=shuffle(people)[0];if(p.id===current?.id&&people.length>1)p=shuffle(people.filter(x=>x.id!==current.id))[0];setCurrent(p);setIndex(0);setOpts(choices(Array.from(p.name)[0],people));setPicked(null);setMessage('');setStatus('playing');setRound(n=>n+1)};
 const choose=(o:Choice)=>{if(picked||!current)return;setPicked(o.value);if(!o.correct){setMessage('再看仔細一點，找找看正確的字！');return}setScore(n=>n+1);setMessage('答對了！');setTimeout(()=>{const n=index+1;if(n>=Array.from(current.name).length){setIndex(n);setStatus('finished');setMessage('你認出他了！')}else{setIndex(n);setOpts(choices(Array.from(current.name)[n],people));setPicked(null);setMessage('')}},650)};
 const answered=current?Array.from(current.name).slice(0,index).join(''):'',total=useMemo(()=>current?Array.from(current.name).length:0,[current]),progress=current?Math.round(index/total*100):0,empty=loaded&&people.length===0;
 return <main className="game-shell"><header className="topbar"><div className="brand-mark"><Users/></div><div><p className="eyebrow">看照片・認名字</p><h1>認識你真好</h1></div><Dialog open={open} onOpenChange={v=>{setOpen(v);if(!v)reset()}}><DialogTrigger className="manage-button"><Settings/>管理題庫 <span>{people.length}</span></DialogTrigger><DialogContent className="manager-dialog"><DialogHeader><DialogTitle>管理真人照片與姓名</DialogTitle><DialogDescription>照片只儲存在這台裝置的瀏覽器。至少加入 3 人才能開始遊戲。</DialogDescription></DialogHeader><div className="editor"><label className={`photo-input ${photo?'has-photo':''}`}>{photo?<img src={photo} alt="照片預覽"/>:<><ImagePlus/><span>選擇照片</span></>}<input type="file" accept="image/*" onChange={upload}/></label><div className="name-editor"><label htmlFor="person-name">姓名</label><input id="person-name" value={name} maxLength={12} placeholder="例如：王小明" onChange={e=>setName(e.target.value)}/><p>遊戲會依照姓名順序，一次選一個字。</p></div><button className="save-button" disabled={!name.trim()||!photo} onClick={save}>{editId?<Check/>:<Plus/>}{editId?'儲存修改':'加入題庫'}</button>{editId&&<button className="cancel-button" onClick={reset}><X/>取消</button>}</div><div className="roster-head"><strong>目前名單</strong><span>{people.length} 人</span></div><div className="roster">{!people.length&&<div className="roster-empty">還沒有資料，請從上方加入第一位。</div>}{people.map(p=><div className="person-row" key={p.id}><img src={p.photo} alt={`${p.name}的照片`}/><strong>{p.name}</strong><button aria-label={`編輯${p.name}`} onClick={()=>edit(p)}><Pencil/></button><button className="delete" aria-label={`刪除${p.name}`} onClick={()=>remove(p.id)}><Trash2/></button></div>)}</div></DialogContent></Dialog></header>
 <section className="game-card"><div className="score-strip"><span>第 {round||1} 題</span><span><Sparkles/>答對 {score} 個字</span></div>{status==='idle'&&<div className="welcome-state"><div className="photo-stage empty-photo"><Users/></div><h2>{empty?'先建立你的真人題庫':'準備好認識大家了嗎？'}</h2><p>{empty?'加入照片和姓名後，就能開始玩。':`題庫裡有 ${people.length} 位，按下開始會隨機抽一位。`}</p><button className="primary-button" onClick={empty?()=>setOpen(true):start}>{empty?<Plus/>:<Play/>}{empty?'加入照片與姓名':'開始遊戲'}</button>{!empty&&people.length<3&&<p className="need-more">還要加入 {3-people.length} 人，才有足夠的三選一題目。</p>}</div>}
 {current&&status!=='idle'&&<div className="play-state"><div className="photo-stage"><img src={current.photo} alt="猜猜這是誰"/></div><div className="prompt-area"><p className="step-label">第 {Math.min(index+1,total)} 個字</p><div className="name-slots">{Array.from(current.name).map((c,i)=><span key={i} className={i<index||status==='finished'?'filled':i===index?'current':''}>{i<index||status==='finished'?c:'?'}</span>)}</div>{status==='playing'&&<><h2>{index===0?'他的名字，第一個字是？':`「${answered}」後面的字是？`}</h2><div className="choice-grid">{opts.map(o=>{const state=picked===o.value?(o.correct?'correct':'wrong'):picked&&o.correct?'reveal':'';return <button key={o.value} className={state} onClick={()=>choose(o)}>{o.value}{state==='correct'&&<Check/>}{state==='wrong'&&<X/>}</button>})}</div><div className={`feedback ${picked?'show':''}`}>{message}{picked&&!opts.find(o=>o.value===picked)?.correct&&<button onClick={()=>{setPicked(null);setMessage('')}}>再試一次</button>}</div></>}{status==='finished'&&<div className="finish-panel"><Sparkles/><h2>{message}</h2><p>他的名字是 <strong>{current.name}</strong></p><button className="primary-button" onClick={start}><RotateCcw/>下一位</button></div>}<div className="progress-track"><span style={{width:`${progress}%`}}/></div></div></div>}</section><p className="privacy-note">小提醒：請在取得本人或家長同意後使用照片；更換瀏覽器或清除瀏覽資料，題庫也會一併清除。</p></main>
}
